# Netlify configuration for a Next.js application

[build]
  # Command to build the Next.js application
  command = "npm run build"
  
  # Directory where the build output is located
  publish = ".next"

  # Environment variables (can also be set in Netlify UI)
  # Example:
  # environment = { NODE_VERSION = "18" }

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true


[[plugins]]
  # Essential Next.js plugin for Netlify
  package = "@netlify/plugin-nextjs"

# Redirects and rewrites can be configured here if needed
# For example, to handle client-side routing correctly:
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Note: The @netlify/plugin-nextjs usually handles most Next.js specific
# configurations automatically, including serverless functions for API routes
# and SSR/ISR pages.
